/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JToolBar;

/**
 *
 * @author joanm
 */
public class Ventana_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        pndEscritorio = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        lblHora = new javax.swing.JLabel();
        lblimg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        opcmSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opcmPaciente = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        opcmRecaudo = new javax.swing.JMenuItem();
        opcListados = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("   00:00:00");
        lblHora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToolBar1.add(lblHora);

        pndEscritorio.add(jToolBar1);
        jToolBar1.setBounds(0, 660, 810, 30);

        lblimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        pndEscritorio.add(lblimg);
        lblimg.setBounds(0, 36, 810, 630);

        jMenu2.setText("Archivo");

        opcmSalir.setText("Salir");
        jMenu2.add(opcmSalir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Registrar");

        opcmPaciente.setText("Paciente");
        jMenu3.add(opcmPaciente);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Consultar");

        opcmRecaudo.setText("Recaudo");
        opcmRecaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcmRecaudoActionPerformed(evt);
            }
        });
        jMenu1.add(opcmRecaudo);

        opcListados.setText("Listado");
        jMenu1.add(opcListados);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pndEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pndEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcmRecaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcmRecaudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcmRecaudoActionPerformed

    /**
     * @param args the command line arguments
     */

    public JDesktopPane getDesktopPane() {
        return pndEscritorio;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.pndEscritorio = desktopPane;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public JMenuItem getOpcmRecaudo() {
        return opcmRecaudo;
    }

    public void setOpcmRecaudo(JMenuItem opcmRecaudo) {
        this.opcmRecaudo = opcmRecaudo;
    }

    public JMenuItem getOpcmSalir() {
        return opcmSalir;
    }

    public void setOpcmSalir(JMenuItem opcmSalir) {
        this.opcmSalir = opcmSalir;
    }

   

    public JMenuItem getOpcmPaciente() {
        return opcmPaciente;
    }

    public JDesktopPane getPndEscritorio() {
        return pndEscritorio;
    }

    public void setPndEscritorio(JDesktopPane pndEscritorio) {
        this.pndEscritorio = pndEscritorio;
    }

    public JLabel getLblimg() {
        return lblimg;
    }

    public void setLblimg(JLabel lblimg) {
        this.lblimg = lblimg;
    }

    
    
    

    /**
     * @param args the command line arguments
     */
    public void setOpcmPaciente(JMenuItem opcmPaciente) {
        this.opcmPaciente = opcmPaciente;
    }

    public JLabel getLblHora() {
        return lblHora;
    }

    public void setLblHora(JLabel lblHora) {
        this.lblHora = lblHora;
    }

    /*public JMenuItem getOpclisHC() {
        return OpclisHC;
    }

    public void setOpclisHC(JMenuItem OpclisHC) {
        this.OpclisHC = OpclisHC;
    }

    public JMenuItem getOpclisLab() {
        return OpclisLab;
    }

    public void setOpclisLab(JMenuItem OpclisLab) {
        this.OpclisLab = OpclisLab;
    }

    public JMenuItem getOpclisPac() {
        return OpclisPac;
    }

    public void setOpclisPac(JMenuItem OpclisPac) {
        this.OpclisPac = OpclisPac;
    }
*/

    public JMenuItem getOpcListados() {
        return opcListados;
    }

    public void setOpcListados(JMenuItem opcListados) {
        this.opcListados = opcListados;
    }
    

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblimg;
    private javax.swing.JMenuItem opcListados;
    private javax.swing.JMenuItem opcmPaciente;
    private javax.swing.JMenuItem opcmRecaudo;
    private javax.swing.JMenuItem opcmSalir;
    private javax.swing.JDesktopPane pndEscritorio;
    // End of variables declaration//GEN-END:variables

}
